## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [13]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
import warnings

warnings.filterwarnings('ignore')

In [14]:
## 線性回歸模型
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)
regr.coef_

array([-1.25856659e-01,  4.84257396e-02,  1.84085281e-02,  3.08509569e+00,
       -1.73277018e+01,  3.61674713e+00,  2.19181853e-03, -1.49361132e+00,
        3.19979200e-01, -1.27294649e-02, -9.27469086e-01,  9.50912468e-03,
       -5.33592471e-01])

In [15]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 17.04


In [16]:
## Lasso模型
lasso = linear_model.Lasso(alpha=2.0)
lasso.fit(x_train, y_train)
y_pred = lasso.predict(x_test)
lasso.coef_

array([-0.02373777,  0.03337257, -0.        ,  0.        , -0.        ,
        0.        ,  0.0464509 , -0.05385332,  0.17209629, -0.01166072,
       -0.55648668,  0.00710112, -0.8213388 ])

In [17]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 28.51


In [18]:
## Ridge模型
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.1, random_state=4)
ridge = linear_model.Ridge(alpha=0.01)
ridge.fit(x_train, y_train)
y_pred = regr.predict(x_test)
ridge.coef_

array([-1.25797872e-01,  4.84438617e-02,  1.78907133e-02,  3.08245158e+00,
       -1.72029332e+01,  3.61779962e+00,  2.07623760e-03, -1.49183513e+00,
        3.19665635e-01, -1.27374414e-02, -9.26163469e-01,  9.51528786e-03,
       -5.33748338e-01])

In [19]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 17.04
